import { useState, useEffect } from 'react';
import { getSessions } from '../services/api';
import { FileText, Download, Eye } from 'lucide-react';

function ReportsPage() {
  const [sessions, setSessions] = useState([]);
  const [selected, setSelected] = useState(null);
  const [checks, setChecks] = useState({
    thermal: true, optical: true, enhanced: true,
    metrics: true, heatmap: true, hotspots: true,
  });

  useEffect(() => {
    getSessions().then(r => {
      const completed = r.data.filter(s => s.status === 'completed');
      setSessions(completed);
      if (completed.length > 0) setSelected(completed[0]);
    }).catch(() => {});
  }, []);

  const toggle = (key) => setChecks(prev => ({ ...prev, [key]: !prev[key] }));

  const generateTextReport = () => {
    if (!selected) return '';
    const lines = ['═══════════════════════════════════════', '  STELLAR VISIONX — FUSION REPORT', '═══════════════════════════════════════', ''];
    lines.push(`Session ID: ${selected._id}`);
    lines.push(`Date: ${new Date(selected.createdAt).toLocaleString()}`);
    lines.push('');
    if (checks.metrics) {
      lines.push('── METRICS ──');
      lines.push(`  PSNR:              ${selected.metrics?.psnr ?? '—'} dB`);
      lines.push(`  SSIM:              ${selected.metrics?.ssim ?? '—'}`);
      lines.push(`  RMSE:              ${selected.metrics?.rmse ?? '—'}`);
      lines.push(`  Thermal Fidelity:  ${selected.metrics?.thermalFidelity ?? '—'}%`);
      lines.push(`  Edge Preservation: ${selected.metrics?.edgePreservation ?? '—'}%`);
      lines.push(`  Accuracy:          ${selected.metrics?.accuracy ?? '—'}%`);
      lines.push(`  Confidence:        ${selected.metrics?.confidence ?? '—'}%`);
      lines.push('');
    }
    if (checks.hotspots) {
      lines.push('── HOTSPOTS ──');
      lines.push(`  Detected: ${selected.metrics?.hotspotsDetected ?? 0}`);
      lines.push('');
    }
    lines.push('── IMAGE URLS ──');
    if (checks.optical) lines.push(`  Optical:  ${selected.opticalImageUrl}`);
    if (checks.thermal) lines.push(`  Thermal:  ${selected.thermalImageUrl}`);
    if (checks.enhanced) lines.push(`  Enhanced: ${selected.resultImageUrl}`);
    if (checks.heatmap) lines.push(`  Heatmap:  ${selected.heatmapUrl || 'N/A'}`);
    lines.push('');
    lines.push('═══════════════════════════════════════');
    lines.push('  Generated by Stellar VisionX');
    lines.push('  Powered by Team Genesis');
    lines.push('═══════════════════════════════════════');
    return lines.join('\n');
  };

  const downloadFile = (content, filename, type) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = filename; a.click();
    URL.revokeObjectURL(url);
  };

  const exportTXT = () => downloadFile(generateTextReport(), `report_${selected._id.slice(-6)}.txt`, 'text/plain');

  const exportCSV = () => {
    if (!selected) return;
    const m = selected.metrics || {};
    const csv = 'Metric,Value\n' +
      `PSNR,${m.psnr}\nSSIM,${m.ssim}\nRMSE,${m.rmse}\n` +
      `Thermal Fidelity,${m.thermalFidelity}\nEdge Preservation,${m.edgePreservation}\n` +
      `Accuracy,${m.accuracy}\nConfidence,${m.confidence}\nHotspots,${m.hotspotsDetected}\n` +
      `Processing Time (ms),${m.processingTimeMs}`;
    downloadFile(csv, `metrics_${selected._id.slice(-6)}.csv`, 'text/csv');
  };

  if (sessions.length === 0) {
    return (
      <div>
        <h1>Reports</h1>
        <div className="card" style={{ padding: '4rem', textAlign: 'center' }}>
          <FileText size={48} color="var(--text-muted)" style={{ marginBottom: '1rem' }} />
          <h2>No Completed Sessions</h2>
          <p>Run a fusion to generate exportable reports.</p>
        </div>
      </div>
    );
  }

  return (
    <div>
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1>Export Reports</h1>
          <p>Select data to include and export in your preferred format.</p>
        </div>
        <select value={selected?._id || ''} onChange={(e) => setSelected(sessions.find(s => s._id === e.target.value))}
          className="input-field" style={{ width: 'auto', maxWidth: 220 }}>
          {sessions.map(s => <option key={s._id} value={s._id}>Session {s._id.slice(-6)}</option>)}
        </select>
      </div>

      <div className="grid grid-sidebar">
        {/* Left: Checkboxes */}
        <div className="card">
          <h2>Include in Report</h2>
          <div className="flex flex-col gap-3 mt-4">
            <p style={{ fontWeight: 600, fontSize: '0.8rem', color: 'var(--text-muted)', textTransform: 'uppercase' }}>Inputs</p>
            {['thermal', 'optical', 'enhanced'].map(k => (
              <label key={k} className="flex items-center gap-3" style={{ cursor: 'pointer', fontSize: '0.9rem' }}>
                <input type="checkbox" checked={checks[k]} onChange={() => toggle(k)} />
                {k.charAt(0).toUpperCase() + k.slice(1)} Image
              </label>
            ))}
            <p style={{ fontWeight: 600, fontSize: '0.8rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginTop: '0.5rem' }}>Data</p>
            {['metrics', 'heatmap', 'hotspots'].map(k => (
              <label key={k} className="flex items-center gap-3" style={{ cursor: 'pointer', fontSize: '0.9rem' }}>
                <input type="checkbox" checked={checks[k]} onChange={() => toggle(k)} />
                {k.charAt(0).toUpperCase() + k.slice(1)}
              </label>
            ))}
          </div>
          <div className="flex flex-col gap-2 mt-6">
            <button className="btn btn-primary" onClick={exportTXT}><Download size={16} /> Export TXT</button>
            <button className="btn btn-secondary" onClick={exportCSV}><Download size={16} /> Export CSV</button>
          </div>
        </div>

        {/* Right: Preview */}
        <div className="card">
          <div className="flex justify-between items-center mb-4">
            <h2 style={{ margin: 0 }}>Report Preview</h2>
            <span className="badge badge-info"><Eye size={14} /> Live Preview</span>
          </div>
          <pre style={{
            background: '#f8fafc', border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)',
            padding: '1.5rem', fontSize: '0.8rem', fontFamily: 'monospace',
            maxHeight: 500, overflowY: 'auto', whiteSpace: 'pre-wrap', lineHeight: 1.6,
          }}>
            {generateTextReport()}
          </pre>
        </div>
      </div>
    </div>
  );
}

export default ReportsPage;
